### ISSUE TITLE
Vehicle Damage only visible AFTER restart

### ISSUE THREAD

**Issue by Markokil321** [f3cuk/WICKED-AI#140] opened 2015-03-08 01:11 UTC
I am running BETA 2.2.0 v3 - DayZ Epoch 1.0.5.1
and have: 
wai_vehicle_damage			= [20,70];
wai_keep_vehicles			= true;
wai_lock_vehicles			= false;

Any vehicle that spawns at a mission will spawn fully green with no visible damage to it, you will still have scroll options to repair damaged parts, however those parts do not look / seem damaged until after first server restart.

IE. Mission spawns an ATV:
ATV is fully green with no visible damage
scrolling on it shows Engine is damaged at 60%, Fueltank at 72%, LWheel at 55%

After server restart:
ATV shows parts are orange/yellow with visible damage
scrolling on it shows Engine is damaged at 60%, Fueltank at 72%, LWheel at 55%

This is causing very many people to think there is a glitch causing their vehicles to be 'suddenly broken' after a restart, is there any way to resolve this? (make vehicles spawn with (visible) damage, and the damage doesn't change over the restart, unless vehicle was repaired/damaged further.)

Fuel amount is correctly spawned/persistent after a restart.

**Comment by f3cuk** [comment] 2015-06-05 23:54
Duplicate of #117

**Closed by f3cuk** 2015-06-05 23:54 UTC
